In [10]:
import pandas as pd 
import numpy as np

In [127]:
#np.nan 空
#np.inf 无穷
s = pd.Series([1,3,5,np.inf,6,8,np.nan,4,12,52],name = 'AAA')
print(s)

0     1.0
1     3.0
2     5.0
3     inf
4     6.0
5     8.0
6     NaN
7     4.0
8    12.0
9    52.0
Name: AAA, dtype: float64


In [12]:
print(type(s))
print(len(s))

<class 'pandas.core.series.Series'>
9


In [14]:
a = np.arange(10,20,1)
b = pd.Series(a,name = 'A')
b

0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
Name: A, dtype: int32

 # 1.2 访问Series元素

In [16]:
#下标访问
b[0:-1]

0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
Name: A, dtype: int32

## 1.3修改元素

In [24]:
print(b)
b[i] = 10000
print('修改后',i)

0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
Name: A, dtype: int32


NameError: name 'i' is not defined

## 1.4 常用统计函数

In [34]:
print("max = ",b.max(),"位置为：",b.argmax())
print("min = ",b.min(),"位置为：",b.argmin())

max =  19 位置为： 9
min =  10 位置为： 0


In [44]:
a = np.random.randint(0,100,size=(5,3))
print (a)
pd.DataFrame(a,columns=['AAA','BBB','CCC'])


[[73 79 28]
 [97 19 54]
 [79 59 79]
 [ 2  6 48]
 [82 26  1]]


AAA  BBB  CCC
0   73   79   28
1   97   19   54
2   79   59   79
3    2    6   48
4   82   26    1

In [128]:
df = pd.DataFrame({'A':5,
                  'B':np.arange(10,20,1),
                  'C':['AA','BB','CC','DD','EE','FF','GG','HH','II','KK'],
                   'D':s,
                   'E':pd.Timestamp('20220321'),
                   'F':True
                  })
df

A   B   C     D          E     F
0  5  10  AA   1.0 2022-03-21  True
1  5  11  BB   3.0 2022-03-21  True
2  5  12  CC   5.0 2022-03-21  True
3  5  13  DD   inf 2022-03-21  True
4  5  14  EE   6.0 2022-03-21  True
5  5  15  FF   8.0 2022-03-21  True
6  5  16  GG   NaN 2022-03-21  True
7  5  17  HH   4.0 2022-03-21  True
8  5  18  II  12.0 2022-03-21  True
9  5  19  KK  52.0 2022-03-21  True

## 2.2 DataFrame 常用属性和方法

In [37]:
df.head(8) #默认是5行

AAA  BBB  CCC
0   40   25   47
1   90   49   84
2   22   30   92
3    6   11   94
4   80   60   73

In [39]:
df.tail(3) #行

AAA  BBB  CCC
2   22   30   92
3    6   11   94
4   80   60   73

In [40]:
df.info() #查看基本信息

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   AAA     5 non-null      int32
 1   BBB     5 non-null      int32
 2   CCC     5 non-null      int32
dtypes: int32(3)
memory usage: 188.0 bytes


In [41]:
#统计数值类型的列的描述性
df.describes() # 只统计数字类型的字段

AttributeError: 'DataFrame' object has no attribute 'describes'

In [42]:
# 看索
df.index

RangeIndex(start=0, stop=5, step=1)

In [45]:
# 看列名
df.columns

Index(['AAA', 'BBB', 'CCC'], dtype='object')

In [46]:
df.values #取二维表的数据部分

array([[40, 25, 47],
       [90, 49, 84],
       [22, 30, 92],
       [ 6, 11, 94],
       [80, 60, 73]])

In [47]:
# 二维表转置
df.T

0   1   2   3   4
AAA  40  90  22   6  80
BBB  25  49  30  11  60
CCC  47  84  92  94  73

In [48]:
#根据索引排序
df.sort_index(axis = 0,ascending=False) #倒叙

AAA  BBB  CCC
4   80   60   73
3    6   11   94
2   22   30   92
1   90   49   84
0   40   25   47

In [49]:
df.sort_values(by='D') #默认空值排在最后

KeyError: 'D'

## 2.3 访问DataFrame
### 2.3.1切片访问

In [50]:
df[1:6]

AAA  BBB  CCC
1   90   49   84
2   22   30   92
3    6   11   94
4   80   60   73

In [51]:
#重置索引
df.iloc[2:-2]

AAA  BBB  CCC
2   22   30   92

In [52]:
# iloc[,] 左边行 右边列
df.iloc[:,2]

0    47
1    84
2    92
3    94
4    73
Name: CCC, dtype: int32

In [53]:
#['列名']
df['A']
df[['A','C','F']]

KeyError: 'A'

In [54]:
df[['A','C']][0:5]

KeyError: "None of [Index(['A', 'C'], dtype='object')] are in the [columns]"

In [57]:
df['A'][[True,False,True,False,True,False,False,False]]

KeyError: 'A'

In [58]:
df['b']>15

KeyError: 'b'

In [60]:
df[df['D']<3]#条件选择

KeyError: 'D'

In [61]:
# D为无穷
df[df['D']==np.inf]

KeyError: 'D'

In [63]:
#判空
df[df['D'].isnull()]

KeyError: 'D'

In [65]:
# 多重条件
df[df['B'>15]&(df['D']>10)]

TypeError: '>' not supported between instances of 'str' and 'int'

In [66]:
#判断是否在列表
df[df['C'].isin(['AA','BB','CC'])]

KeyError: 'C'

In [67]:
#判断字符串
df[df['C'].str.startswith('A')]

KeyError: 'C'

## 2.4修改DataFrame

In [68]:
df2 = df.copy()
print(df2,'\n')

   AAA  BBB  CCC
0   40   25   47
1   90   49   84
2   22   30   92
3    6   11   94
4   80   60   73 



In [69]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   AAA     5 non-null      int32
 1   BBB     5 non-null      int32
 2   CCC     5 non-null      int32
dtypes: int32(3)
memory usage: 188.0 bytes


In [70]:
#按行修改
df2.iloc[0]=2000
df2

AAA   BBB   CCC
0  2000  2000  2000
1    90    49    84
2    22    30    92
3     6    11    94
4    80    60    73

In [72]:
#按列
df2['A'] = 'AAAAA'
df2

AAA   BBB   CCC      A
0  2000  2000  2000  AAAAA
1    90    49    84  AAAAA
2    22    30    92  AAAAA
3     6    11    94  AAAAA
4    80    60    73  AAAAA

In [77]:
df2['BBB'] [df['BBB']>30]


1    49
4    60
Name: BBB, dtype: int32

## 2.4.2 根据条件设置

In [78]:
df2['BBB'] [df['BBB']>30]

1    49
4    60
Name: BBB, dtype: int32

## 2.5 pandas 缺失值处理

### 2.5.1 查看缺失值

In [79]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   AAA     5 non-null      int32
 1   BBB     5 non-null      int32
 2   CCC     5 non-null      int32
dtypes: int32(3)
memory usage: 188.0 bytes


In [81]:
df.isnull().sum()

AAA    0
BBB    0
CCC    0
dtype: int64

### 删除有nan的行或列

In [83]:
df.dropna(axis=0,how = 'any',inplace=False )#列

AAA  BBB  CCC
0   40   25   47
1   90   49   84
2   22   30   92
3    6   11   94
4   80   60   73

In [84]:
df.dropna(axis=1,how = 'any',inplace=False ) #行

AAA  BBB  CCC
0   40   25   47
1   90   49   84
2   22   30   92
3    6   11   94
4   80   60   73

## 2.5.3替换nan值为0

In [86]:
df.fillna(0)

AAA  BBB  CCC
0   40   25   47
1   90   49   84
2   22   30   92
3    6   11   94
4   80   60   73

### 2.6 文件读取

### 2.6.1 读取excl

In [93]:
data = pd.read_csv('./data/student.csv')
data.head()

Student ID  name   age  gender
0        1100  Kelly   22  Female
1        1101    Clo   21  Female
2        1102  Tilly   22  Female
3        1103   Tony   24    Male
4        1104  David   20    Male

In [94]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Student ID  14 non-null     int64 
 1   name        14 non-null     object
 2   age         14 non-null     int64 
 3   gender      12 non-null     object
dtypes: int64(2), object(2)
memory usage: 576.0+ bytes


In [97]:
data[data['gender']=='Male']

Student ID  name   age gender
3         1103   Tony   24   Male
4         1104  David   20   Male
7         1107      N   43   Male
8         1108      A   13   Male
9         1109      S   12   Male
12        1112      Q   23   Male

In [100]:
#value_counts() 统计人数
data['gender'].value_counts() #忽略空值

Female    6
Male      6
Name: gender, dtype: int64

In [101]:
data['age'].value_counts()

22    3
21    2
3     2
24    1
20    1
43    1
13    1
12    1
33    1
23    1
Name: age, dtype: int64

In [103]:
# 填充
data['gender'].fillna('Male',inplace=True)
data

Student ID  name   age  gender
0         1100  Kelly   22  Female
1         1101    Clo   21  Female
2         1102  Tilly   22  Female
3         1103   Tony   24    Male
4         1104  David   20    Male
5         1105  Catty   22    Male
6         1106      M    3  Female
7         1107      N   43    Male
8         1108      A   13    Male
9         1109      S   12    Male
10        1110  David   33    Male
11        1111     Dw    3  Female
12        1112      Q   23    Male
13        1113      W   21  Female

In [115]:
#将年龄30岁以上的学生的ID+2000
data['Student ID'][data['age']>30]+= 2000
data

C:\Users\78658\AppData\Local\Temp/ipykernel_10816/3140835518.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Student ID'][data['age']>30]+= 2000


Student ID  name   age  gender
0         1100  Kelly   22  Female
1         1101    Clo   21  Female
2         1102  Tilly   22  Female
3         1103   Tony   24    Male
4         1104  David   20    Male
5         1105  Catty   22    Male
6         1106      M    3  Female
7         3107      N   43    Male
8         1108      A   13    Male
9         1109      S   12    Male
10        3110  David   33    Male
11        1111     Dw    3  Female
12        1112      Q   23    Male
13        1113      W   21  Female

In [116]:
#新增列
data['new_col'] = data['Student ID'] / 100
data

Student ID  name   age  gender  new_col
0         1100  Kelly   22  Female    11.00
1         1101    Clo   21  Female    11.01
2         1102  Tilly   22  Female    11.02
3         1103   Tony   24    Male    11.03
4         1104  David   20    Male    11.04
5         1105  Catty   22    Male    11.05
6         1106      M    3  Female    11.06
7         3107      N   43    Male    31.07
8         1108      A   13    Male    11.08
9         1109      S   12    Male    11.09
10        3110  David   33    Male    31.10
11        1111     Dw    3  Female    11.11
12        1112      Q   23    Male    11.12
13        1113      W   21  Female    11.13

In [120]:
#删除列 drop
data.drop(['new_col'],axis = 1,inplace=True)#按列 axis = 1
data

Student ID  name   age  gender
0         1100  Kelly   22  Female
1         1101    Clo   21  Female
2         1102  Tilly   22  Female
3         1103   Tony   24    Male
4         1104  David   20    Male
5         1105  Catty   22    Male
6         1106      M    3  Female
7         3107      N   43    Male
8         1108      A   13    Male
9         1109      S   12    Male
10        3110  David   33    Male
11        1111     Dw    3  Female
12        1112      Q   23    Male
13        1113      W   21  Female

## 2.6.2 导出数据


In [122]:
#保存到csv中 to_csv 
data.to_csv('./data/student1.csv',index=False)

### 2.7pandas 合并操作pd.concat

In [125]:
#定义资料集
df1 = pd.DataFrame(np.ones(2,4),columns=['A','B','C','D'])
df2 = pd.DataFrame(np.ones(2,4)*2,columns=['A','B','C','D'])
df3 = pd.DataFrame(np.ones(2,4)*3,columns=['A','B','C','D'])
df1,df2,df3

TypeError: Cannot interpret '4' as a data type

In [124]:
#concat 纵向合并
pd.concat([df1,df2],axis=1)

NameError: name 'df1' is not defined

In [ ]:
# 横向合并