# WEEK01-Numpy课堂练习

- 中文官网：https://www.numpy.org.cn/
- 英文官网：http://www.numpy.org
- 中文快速入门：https://www.numpy.org.cn/user/quickstart.html

In [2]:
# 引入工具包  # 别名np
import numpy as np

### 1. Numpy创建数组

#### 1.1 一维array创建：使用np.array()

In [8]:
# 创建数组[2,3,4]
a = np.array([2,3,4])
print(a)
print(type(a))  # 查看a的类型
print(a.dtype)  # 查看数据类型

# 创建数组[1.2, 3.5, 5.1]
b = np.array([2.5,4,8])
print(type(b))
print(b.dtype)  # 查看数据类型

[2 3 4]
<class 'numpy.ndarray'>
int32
<class 'numpy.ndarray'>
float64


In [10]:
# 找错误
a = np.array([1,2,3,4])    
a = np.array([1,2,3,4])  

**也可以在创建时显式指定数组的类型：dtype参数**

In [15]:
# 创建数组时，指定数据类型：dtype参数
a = np.array([2,3,4], dtype=np.float64)
print(a)
print(a.dtype)

[2. 3. 4.]
float64


#### 1.2 多维array创建

In [24]:
# 多维array
a = np.array([[2,3,4],[3,4,5],[7,4,5]])
print(a)

# 查看数组的行数、列数 .shape
print("数组的行数、列数:", a.shape) 

[[2 3 4]
 [3 4 5]
 [7 4 5]]
数组的行数、列数: (3, 3)


#### 1.3 创建全零数组: np.zeros

In [38]:
# 经常用在数组的初始化,默认dtype=float64
a = np.zeros((3, 4))
print(a) # 生成3行4列的全零矩阵
print(a.dtype)

# 设置int32
a = np.zeros((3.4), dtype=np.int32)
print(a) # 生成3行4列的全零矩阵
print(a.dtype)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
float64


TypeError: 'float' object cannot be interpreted as an integer

#### 1.4 创建全1数据: np.ones

In [30]:
# 创建全一数据，同时指定数据类型
a = np.ones((3,4), dtype=np.int32)
# np.int 等同np.int32
print(a)
print(a.shape)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
(3, 4)


#### 1.5 创建全空数组：np.empty

In [40]:
# 创建全空数组，其初始内容是随机的，取决于内存的状态
a = np.empty((6,4))

print(a)

[[ 7.63813952e-312  7.16395186e-322  0.00000000e+000  0.00000000e+000]
 [ 7.61796489e-312  1.16095484e-028 -2.85639645e+181 -4.18516477e-026]
 [-3.49925557e-015 -3.06387316e+181 -7.61659224e-031 -1.86814240e-169]
 [-1.49061127e+181 -1.03249646e-237 -4.54923531e-179  4.07111566e+137]
 [ 5.28595592e-085  8.26482251e-048  4.11083805e+223  6.42899419e-109]
 [ 6.48224637e+170  3.67145870e+228  3.68351186e-033              nan]]


#### 1.6 创建连续数组： np.arange

In [43]:
# 创建连续数组 arange
# 10-20的数据，步长为1，不包含最后的数字
a = np.arange(10, 20, 1)
print(a, a.shape)

# 简化场景：只写一个参数，从0开始
# 10-20的数据，步长为1，不包含最后的数字
b = np.arange(10)

print(b, b.shape)

# 练习：1,3,5,7,9,11,13
x = np.arange(1, 14, 2)
print(x)

[10 11 12 13 14 15 16 17 18 19] (10,)
[0 1 2 3 4 5 6 7 8 9] (10,)
[ 1  3  5  7  9 11 13]


#### 1.7 创建线段型数据 np.linspace

In [58]:
# 创建线段型数据 linspace
# 开始端1，结束端10，且分割成10个数据，生成线段
a = np.linspace(1, 10, 19)
print(a, a.shape)

# linspace和arange的对比 0-10,分20等分
b = np.arange(0, 10.5, 0.5)
print(b, b.shape)
c = np.linspace(0, 10, 21)
print(c, c.shape)

[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10. ] (19,)
[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10. ] (21,)
[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10. ] (21,)


### 2. 数组的基本属性

In [46]:
a = np.array([[2,3,4],
              [3,4,5]] , dtype = np.int)
# 维度
print('number of dim:', )

# 行数和列数
print('shape:',)

# 元素个数
print('size:',)

number of dim: 2 2
shape: (2, 3)
size: 6


### 3.Numpy索引与切片

In [3]:
# 先创建两个数组
a = np.arange(10,20,1)   # 不包含10
b = np.array([[2,3,4,5,6],
              [20,30,40,50,60],
              [200,300,400,500,600]] , dtype = np.int)
print(a)
print(b)

[10 11 12 13 14 15 16 17 18 19]
[[  2   3   4   5   6]
 [ 20  30  40  50  60]
 [200 300 400 500 600]]


C:\Users\HP\AppData\Local\Temp/ipykernel_1688/1451444470.py:5: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  [200,300,400,500,600]] , dtype = np.int)


In [9]:
# 用[index]来选取某个元素，用：切片，同list
print(a[0])
print(a[0:3])
print(a[-1])
print(a[1:-2])

10
[10 11 12]
19
[11 12 13 14 15 16 17]


In [16]:
# 多维数组
print(b[1])
print(b[1][2])
print(b[1, 0:-1]) # ,左边是行 右边是列

[20 30 40 50 60]
40
[20 30 40 50]


In [22]:
# 练习：输出第二列；输出中间的3 4 30 40
print(b[:,1])
print(b[0:2, 1:3])

[  3  30 300]
[[ 3  4]
 [30 40]]


### 4. Numpy基本运算

#### 4.1 一维矩阵运算

In [25]:
# 一维矩阵运算
a = np.array([10,20,30,40])
b = np.array([1,2,3,4])
print(a,b)

[10 20 30 40] [1 2 3 4]


In [29]:
# 矩阵和常数运算
a + 2

array([12, 22, 32, 42])

In [30]:
a * 2

array([20, 40, 60, 80])

In [31]:
# 逐项加减乘除 需要有相同的shape
print("加法：", a + b)
print("减法：", a - b)
print("元素相乘：", a * b)
print("元素相除：", a / b)

加法： [11 22 33 44]
减法： [ 9 18 27 36]
元素相乘： [ 10  40  90 160]
元素相除： [10. 10. 10. 10.]


In [32]:
# 在Numpy中，想要求出矩阵中各个元素的乘方需要依赖双星符号 **，以二次方举例，即：
c = b ** 2
print(c)

[ 1  4  9 16]


In [81]:
# Numpy中具有很多的数学函数工具
print(np.sin(a))
print(np.log(b))

[-0.54402111  0.91294525 -0.98803162  0.74511316]
[0.         0.69314718 1.09861229 1.38629436]


In [33]:
# 比较表达式，输出True False
a = np.array([1,1,4,3])
b = np.array([1,2,3,4])

print(b<2)
print(a==b)

[ True False False False]
[ True False False False]


#### 4.2 多维矩阵运算

In [86]:
a = np.array([[1,1],
              [0,1]])
b = np.array([[1,2],
              [3,4]])
print(a)
print(b)

[[1 1]
 [0 1]]
[[1 2]
 [3 4]]


In [37]:
# 矩阵加法： 逐项相加,需要a，b 行数、列数是相同
print("加法：\n", a + b)
print("元素的逐项乘法：\n", a * b)   # elementwise product
print("矩阵的乘法：\n", a @ b)  # matrix product
print("矩阵的乘法（另一种写法）：\n", np.dot(a, b))

ValueError: operands could not be broadcast together with shapes (3,2) (2,1) 

In [34]:
# 练习：矩阵乘法
a = np.array([[1,1],[0,1],[2,2]])
b = np.array([[0],[1]])
print(a)
print(b)
print("矩阵乘法：\n", a@b)

[[1 1]
 [0 1]
 [2 2]]
[[0]
 [1]]
矩阵乘法：
 [[1]
 [1]
 [2]]


#### 4.3 数据统计函数

In [43]:
# randint: 生成随机的整数
a = np.random.randint(0, 100, size=(3,4))
print(a)

[[34 36 30 70]
 [ 4 71 14 26]
 [53 90  5 12]]


In [45]:
print("总和  ", np.sum(a)) 
print("平均数  ", np.mean(a))
print("中位数  ", np.median(a))  # 22，24，25，37，49，68，86，91
print("标准差  ", np.std(a))  # 标准差、
print("方差  ", np.var(a))   # 方差、
print("最小值  ", np.min(a))
print("最大值  ", np.max(a))

总和   445
平均数   37.083333333333336
中位数   32.0
标准差   27.013756783453047
方差   729.7430555555555
最小值   4
最大值   90


In [51]:
print("最小值的索引号：",  np.argmin(a, axis=1))
print("最大值的索引号：",  np.argmax(a, axis=0))

最小值的索引号： [2 0 2]
最大值的索引号： [2 2 0 0]


- 如果你需要对行或者列进行查找运算，就需要在上述代码中为 axis 进行赋值。
- 当**axis=1**的时候，将会以**行**作为查找单元。
- 当**axis=0**的时候，将会以**列**作为查找单元，

In [52]:
# axis = 1  表示按行进行统计
print("计算每行的和=", np.sum(a, axis=1))
print("计算每列的和=", np.sum(a, axis=0))  

计算每行的和= [170 115 160]
计算每列的和= [ 91 197  49 108]


In [53]:
# 练习：计算每列的最小值，并标出最小元素索引
print("每列的最小值=", np.min(a,axis=1))  # 按列
# 最小元素索引
print(np.min(a, axis=0)) # # 按列

每列的最小值= [30  4  5]
[ 4 36  5 12]


In [54]:
# 练习：计算每行的最大值，并标出最大元素索引
print("每行的最大值=", np.argmax(a, axis=1))  # 按行
# 最大元素索引
print(np.argmin(a, axis=0)) 

每行的最大值= [3 1 1]
[1 0 2 2]


### 5. 数组的操作

#### 5.1 数组整形  **reshape、flatten**

In [57]:
# 使用reshape改变上述数据的形状
a = np.arange(10,22,1) # 10-20的数据，步长为2
print(a, a.shape)

[10 11 12 13 14 15 16 17 18 19 20 21] (12,)


In [71]:
# 整形成2行6列，3行4列
 # 按列来整形的话 order = 'F'
b = np.reshape(a, (2, 6), order='f') # 默认order="C"
c = a.reshape((-1, 4)) # -1不确定的方面用-1 自动排
print(b)
print(c)

[[10 12 14 16 18 20]
 [11 13 15 17 19 21]]
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [66]:
# 拍扁到一维，展平函数
print(b.flatten())   
print(c.flatten())

[10 12 14 16 18 20 11 13 15 17 19 21]
[10 11 12 13 14 15 16 17 18 19 20 21]


#### 5.2 数据转置 np.transpose

In [67]:
# 矩阵转置
print(b,b.shape)
d = b.T
print(d,d.shape)

[[10 12 14 16 18 20]
 [11 13 15 17 19 21]] (2, 6)
[[10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]] (6, 2)


In [68]:
# 更常用的转置 a.T
print(np.transpose(b))

[[10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]]


#### 5.3 数组排序 np.sort

In [85]:
# 生成随机整数，0-100之间 2行4列
a = np.random.randint(0, 100, size=(2, 4))
print("a: ",a)
np.sort(a)
print("排序后: ",a)

a:  [[36 44 82  5]
 [21 53 81 77]]
排序后:  [[36 44 82  5]
 [21 53 81 77]]


In [86]:
print("排序后：\n", np.sort(a, axis=1))  # 默认是按照行来进行排序

排序后：
 [[ 5 36 44 82]
 [21 53 77 81]]


In [87]:
print("按列排序后：\n", np.sort(a, axis=0))  # 按列

按列排序后：
 [[21 44 81  5]
 [36 53 82 77]]


In [88]:
# np.sort不支持倒序排序，所以只能负负得正 
print("倒序排序：\n", -np.sort(-a))

倒序排序：
 [[82 44 36  5]
 [81 77 53 21]]


### 6. 组合数组
- 使用hstack函数实现数组横向组合：np.hstack((arr1,arr2))
- 使用vstack函数实现数组纵向组合：np.vstack((arr1,arr2))
- 使用concatenate函数实现数组横向组合：np.concatenate((arr1,arr2),axis = 1))
- 使用concatenate函数实现数组纵向组合：np.concatenate((arr1,arr2),axis = 0))


In [89]:
a = np.arange(10).reshape(2, 5)
b = np.arange(10,20,1).reshape(2, 5)
print(a)
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[10 11 12 13 14]
 [15 16 17 18 19]]


In [90]:
  # 横向拼接，要求两个矩阵的行相同
np.hstack((a, b))

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

In [91]:
   # 纵向拼接，要求两个矩阵的列数相同
np.vstack((a, b))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [94]:
  # 横向  == hstack
np.concatenate((a,b), axis=1)

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

In [95]:
   # 纵向 == vstack
np.concatenate((a,b), axis=1)

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

### 7. 文件读写 np.savetxt  np.loadtxt

In [99]:
a = np.random.random(10).reshape(2, 5)  # np.random.random 生成（0，1）之间的数据
print(a)
# 保存到/data/tmp1.txt中
np.savetxt('data/tmp1.csv', a)
np.savetxt('data/tmp1.csv', a)

[[0.84633008 0.89864805 0.44811377 0.58146169 0.13542572]
 [0.28771426 0.81566369 0.75851313 0.1389316  0.23734225]]


In [98]:
# 从/data/tmp1.txt中读取数据
b = np.loadtxt('data/tmp1.text')
print(b)

[[0.11556675 0.93243202 0.6141953  0.18193695 0.6473246 ]
 [0.10636868 0.80406329 0.60622686 0.70323782 0.18474314]]
